### ISSUE TITLE
Grafikbug

### ISSUE THREAD

**Issue by janso3** [PodeCaradox/Gm1KonverterCrossPlatform#5]
![bug](https://user-images.githubusercontent.com/25061393/58726972-6661a180-83e3-11e9-8f29-f499a9a22e62.PNG)

**Comment by PodeCaradox** [comment]
der bug ist nur im programm wen du exportest ist dort kein schwarzer balken. Das Problem liegt an avalonia, da der renderer noch fehler hat x). Das mit den Positionen hab ich auch noch nicht gemacht, falls du es in deinem opensource projekt lädst.
