### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by JuGGerNaunT** [PodeCaradox/Gm1KonverterCrossPlatform#7]
After some time of switching between gm1 file program crashes. There is no specific pattern and it happens on random file.
PS: game - Stronghold Crusader HD

**Comment by PodeCaradox** [comment]
Do the Gm1Converter crash or stronghold? You just switch between Gm1 files and the programm crashes? I will add the log file in the next update ;)

**Comment by JuGGerNaunT** [comment]
Gm1Converter crash at some point when I just select a file in this list
![list](https://user-images.githubusercontent.com/1506510/63187900-ab9f8200-c068-11e9-8595-678341c9eafc.png)

**Comment by PodeCaradox** [comment]
platform. windows?

**Comment by JuGGerNaunT** [comment]
Yes

**Comment by PodeCaradox** [comment]
ok i will have a look for the new update, it will be published next week.

**Comment by PodeCaradox** [comment]
Is the crash still in the Programm or can i close the issue, if so pls activate the Logger :)

**Comment by JuGGerNaunT** [comment]
I don't use this tool so actively anymore so I can't reproduce this issue. But there is an issue with logger itself. Logger uses localDate.ToShortDateString(). This method is locale specific and it return date in "dd/m/year" format for me. Such string leads to crash since appendtext can't create file in the directory that doesn't exist.

**Comment by PodeCaradox** [comment]
oh yeah such a stupid misstake, i didn forght about the platforms mainly selected language english. Thx for writing it.
