### ISSUE TITLE
anim_castle.gm1 crash

### ISSUE THREAD

**Issue by JuGGerNaunT** [PodeCaradox/Gm1KonverterCrossPlatform#8]
Whenever I click anim_castle.gm1 item program crashes.
This place
https://github.com/PodeCaradox/Gm1KonverterCrossPlatform/blob/fcab4be95fcd1df56a788a7eb22c31b39f92c731/Gm1KonverterCrossPlatform/Views/MainWindow.xaml.cs#L631
I use it for Stronghold Crusader so I don't have Extreme exe

**Comment by PodeCaradox** [comment]
I forgot to check if the path is to the Stronghold Crusader  and Stronghold Crusader Extreme.exe. Sorry for that,

**Comment by JuGGerNaunT** [comment]
Fixed in the last release. Thanks
