### ISSUE TITLE
GFX image crash

### ISSUE THREAD

**Issue by JuGGerNaunT** [PodeCaradox/Gm1KonverterCrossPlatform#9]
1. Click any tgx item
2. Select other item using arrow keys (on keyboard)
3. Click on image
Crash at
https://github.com/PodeCaradox/Gm1KonverterCrossPlatform/blob/fcab4be95fcd1df56a788a7eb22c31b39f92c731/Gm1KonverterCrossPlatform/Views/MainWindow.xaml.cs#L641

**Comment by PodeCaradox** [comment]
Ok i have a look, probably because FileHeader is null for tgx Images.

**Comment by JuGGerNaunT** [comment]
Fixed in the last release. Thanks
